
image:
  repository: ""
  tag: "latest"
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: LoadBalancer
  port: 5000
  targetPort: 5000

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"

livenessProbe:
  path: /healthz
  port: 5000
  initialDelaySeconds: 5
  periodSeconds: 10

readinessProbe:
  path: /healthz  
  port: 5000
  initialDelaySeconds: 5
  periodSeconds: 10

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50

acr:
  server: "acrmilos.azurecr.io"
  username: "acrmilos" 
  password: ""